### ISSUE TITLE
Comment Scanning Assumption Edge Case

### ISSUE THREAD

**Issue by mcn8** [jdistler/xrb_reddit_tipbot#5]
https://github.com/jdistler/xrb_reddit_tipbot/blob/d10efb8c8123961147c11569bc43cd471926fcc1/comments_scanner.py#L261

Here the bot assumes that if there are at least 2 words after a "!tipxrb" command then the comment follows the format "!tipxrb user amount." However, there is the edge case that looks like this that would fail: "!tipxrb 0.5 love this content" which would assume that the user was "0.5" and the amount was "love."

In looking for a solution to this, I believe the easiest fix for users is standardizing tips to be of two formats:

1. !tipxrb <amount> - functions as already expected
2. !tipxrb <user with /u/ required> <amount> - This way comment parsing can be modified to allow users to freely add as much text before or after the command as they wish.

From what I've seen in past comments, rarely have users left off the "/u/" so it seems more useable than forcing users to not write text after the tip command.

**Comment by jdistler** [comment]
You bring up a good point that "!tipxrb 0.5 love this content" would assign user=0.5 and amount=love. This would fail my input checks since the string "love" can't be parsed to a float. I'll add additional logic in the case of  `command_index + 2 < length` to check whether the text that directly follows after !tipxrb is a float or not. If it is a float, I can retrieve the submission author and use that information. If the text is not a float, I can assume the target tipping format is `!tipxrb <user> <amount>`, so I'll assign the user and check if amount is a float.

There is an additional check that the user is a valid registered reddit account by hitting a reddit API endpoint. I don't think I need to enforce the '/u/' prefix, because I can assume the value between !tipxrb and a valid float amount is the desired target user.

**Comment by mcn8** [comment]
Oh yeah, good point. Just checking for a float works great!
